### ISSUE TITLE
Bug: wrong source in edit view [MapX test]

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#155]
### Current Behavior
**Version: /test/**
In the edit view form, a wrong source is listed under "source layer".
If you save without paying attention, your view will be completely changed.
![capture3](https://user-images.githubusercontent.com/19908801/33516692-6d661336-d777-11e7-8388-6ad5375b3269.PNG)

**Comment by fxi** [comment]
Mmh, not good. Seems to be an event scheduling issue. But the logic did not change much since many months. First time you see this ?

Is the source layer selected always:
- the first of the list of choices ?
- the same as the previous view ?
- completely random ?
- a layer previously set and changed later ?

Other questions: 
Is the list of choices: 
- not related to the current country ?
- not related to the current user role ?

**Comment by fxi** [comment]
You can also check this : 
what is the target value in the DB for this source ?

**Comment by fxi** [comment]
Ok. I think I've figured this out. Theoretically. I did not check in DB. What could have happened is that the access rules in the source metadata has changed and you where excluded from the "read" target group. So the layer is not listed, and the default is to replace the layer selected by the first of the available list.

**Comment by thomaspiller** [comment]
I had a closer look at this issue.
It seems to be related to views that are shared between countries (but maybe there's something more).
A few days ago you had to MapX the possibility to edit views shared from other countries and by doing so, the problem is that the source layer is not present in the list. So by default, we end up with the first element of the drop-down list as the source layer.

**Comment by antobenve** [comment]
I confirm the problem that Thomas reported is related to the possibility of editing views in other countries than the one where the source layer was published. I wanted to report it last week but I couldn't find the time.
As we discussed, it is very useful to be able to edit the views everytime we see them. However, something must be changed in order to avoid such potential mistakes.
First option, is to have access to all source layers in every country. I don't know if you want to have this solution as the layers may be several.
Second option is to report the name of the country where the source layer was published. This could be added in the panel of the metadata info of the view. 
Third option, is to have a block for source layer edition (just read the name of it, but not be able to change it) when the configuration of the view is open in a secondary country. In this way, mistakes will be avoid and the views will always be able to be edited for the rights, abstracts,titles and collections. Only the source layer and the variables will be blocked. However, it will be useful to report the name of the country where these variables could be changed in the view configuration .

**Comment by fxi** [comment]
I will close this one as it is solved.
It does not solve the edit functionality from a secondary countries.
