### ISSUE TITLE
Bug reported (story map): overlap between the slides

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#224]
A MOOC user reported this bug: it seems that there is an overlap between the slides in all the steps.
This user uses Google Chrome browser

![isis_dias_matos](https://user-images.githubusercontent.com/25179050/37953953-996651da-31a4-11e8-871d-c07380599cba.jpg)

**Comment by antobenve** [comment]
I am having the same problem with other story maps too.

**Comment by fxi** [comment]
Could you be a bit more technical ?
Which story map ?
Is it happening each times ?
Is there something unusual in the console ?

Thanks.

**Comment by antobenve** [comment]
**Problem:**
When a story map is played, every object of a step (except for views on map) is shown on a small portion of the screen (a quarter of the size of the screen, localised at the screen's bottom-right). 

**Concerned stories:**
For World:
Every story except the following ones has the problem reported by Marion:
- 1) Mooc: introducing MapX video
- 2) General story map: MapX presentation
- 3) Story map Humanitarian Networks and Partnership week

Among these other three stories, only the number 3 one works properly.

The number 2 doesn't start at all when clicking on "play" (nothing changes after clicking play). 
However, it plays on preview. In this case, it shows the same problematic reported by Marion.

The number 1 starts, but when it is played:
      - The map can be dragged if one clicks close to the center of the screen even if the map is locked.
      - There is an icon of a not-properly-visualized image at the very center of the screen.
      - There are no buttons visible at the botton of the screen.
If the first one is previewed, it shows the problem reported by Marion.

**Occurrence:**
The problem is not systematic. The problem disappears after the page is refreshed. The problems occurs again on all the reported stories, when one of the two stories that does not work at all (1-2) are played.

**Comment by MarionPlanque** [comment]
Thank you for these precisions; from my side I cant' manage to reproduce this bug on my computer

**Comment by antobenve** [comment]
Update: only the story number 1 triggers the error

**Console:** 
_View name:_ 

- MOOC: introducing MapX video
This view triggers the malfunctioning of the other views.
![image](https://user-images.githubusercontent.com/30286565/37967257-1cf87d18-31cb-11e8-9fe3-9c5a7ff26b90.png)

Playing the following views promoted the following errors even if the views played properly. 
- Is my water safe to drink?
![image](https://user-images.githubusercontent.com/30286565/37967160-d7c10346-31ca-11e8-8e1a-b5abcffdcf69.png)

- Monitoring pollution with earth observation
![image](https://user-images.githubusercontent.com/30286565/37967553-0a4339c8-31cc-11e8-97e4-3378c682a43d.png)

- Is my water safe to drink?
![image](https://user-images.githubusercontent.com/30286565/37967620-423966d6-31cc-11e8-8528-56babeb91df2.png)

- How can MapX support national action plans of the minamata convenction?
![image](https://user-images.githubusercontent.com/30286565/37967687-68fa81f6-31cc-11e8-9ddf-9272571a39a3.png)



- General story map: MapX presentation
No error. This view doesn't play at all.


Other views do not show any error.

**Comment by fxi** [comment]
@antobenve Please, please.. Read what your are copy pasting. Remove all issues from google then try again. 

Then, as already asked, use GIST (or similar) to provide your logs...

Then : 

- General story map: MapX presentation. This was not not updated for the new story map "engine".
- MOOC: introducing MapX video : same (I've saved it just to be sure).
- What's the story number 1 ?

**Comment by antobenve** [comment]
@fxi 
- Those errors generate exactly when I click on the story maps. I thought they could be related because they occurred simultaneously.

- The problem was evidently triggered by running a story map that was not saved in the new story map engine. Now that you saved the story map "MOOC: introducing MapX video" the error doesn't occur anymore.

- The other story map (General story map: MapX presentation) still doesn't work at all after I saved it.  Nothing happens both on screen and in the console when the story is played.

- The "MOOC: introducing MapX video" plays properly although the content must be set according to the specifics of the new engine. However, errors are still rised when the story is played.
![image](https://user-images.githubusercontent.com/30286565/37971352-040e1050-31d6-11e8-8a6b-4172b3ef9135.png)

**Comment by fxi** [comment]
@antobenve The errors reported above – that you pasted in an image – say that images are not found, and therefore, the story was not updated by the last editor. The images should be replaced and the story updated.

Note: please avoid pasting errors as an image : they can not be read by the search tool. So if someone as the same "error" she will not find this thread.

**Comment by antobenve** [comment]
@fxi 
Ok, thanks for the tip. I'll paste text next time. 
I'll also tell Marion to do so if she wants to use those old stories.

The problem that I could reproduce was only related to story maps that were not saved for the new story map engine. 

However, Marion told me that the student that initially reported the problem was using a story map that works very well for us and for which we cannot reproduce the error.

For this story map I have the following error in the console. However, the error is also common for other story maps. Do you think this particular error might cause the issue for that user?

```
Uncaught Error: Error
    at e.<anonymous> (app.bundle.js:1)
    at e.a.fire (31.bundle.js:1)
    at e.a.fire (31.bundle.js:1)
    at e.a.fire (31.bundle.js:1)
    at e.a.fire (31.bundle.js:1)
    at e._tileLoaded (31.bundle.js:1)
    at e.r (31.bundle.js:1)
    at s.receive (31.bundle.js:1)
```

To discover what could be the problem we asked the student to report the console log when he opens that story map and to report on which other story map trigger the error. We'll post here the updates.
