### ISSUE TITLE
MapX V5: list of improvements

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#258]
- [ ] sort by ...: no indication of which filter is active (possible solution: color of active filter = red)

<!--![tempsnip](https://user-images.githubusercontent.com/19908801/41925050-c3713d28-796b-11e8-8b7f-9cd6f9bc2870.png)->

**Comment by MarionPlanque** [comment]
The issue "List of views accessible when creating a story map: replace the ID of the project by its name e.g (MX-TKA-1FQ-5ZB-ADF-NBY) Areas of interest for mining activities" is not an "improvement" I think, it really is a problem to find the views in the entire list, also because it is the first thing that appears in the view search bar

**Comment by fxi** [comment]
I've hidden non-needed changes in the first post and moved the story map select issue in priority 1.

**Comment by MarionPlanque** [comment]
@fxi Thomas (@thomaspiller ) explained to me the pb of the deadline, so we suggest to do a separate post for this story map issue, this way it doesn't have the pb of the deadline

**Comment by thomaspiller** [comment]
Moved to #383
