### ISSUE TITLE
Filter options: title of the various components

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#261]
MapX allows filtering views according to a series of components; however, the name of these filters remain unclear and users don't understand how to filter views.
**Solution**: rename the filter components:
- _Classe_: Theme OR Topic
- _Collection_: ok
- _Components_: Type of data

**Comment by MarionPlanque** [comment]
@fxi can't find the 'components' words in the dict.main.json file

**Comment by fxi** [comment]
Components does not exits, yet. You can add it as:
```json
  {
    "id": "component",
    "en": "Component",
    "fr": "Composant",
    "es": "",
    "ru": "",
    "zh": "",
    "de": "",
    "bn": "",
    "fa": "",
    "ps": ""
  },
  {
    "id": "components",
    "en": "Components",
    "fr": "Composants",
    "es": "",
    "ru": "",
    "zh": "",
    "de": "",
    "bn": "",
    "fa": "",
    "ps": ""
  }
```
Plural form is not mandatory, as it's not widely needed. 

"Type of data" is not right here because the types in MapX client side are raster, vector, story map and custom code. With component, we list also view featuring dashboards and custom style, which are not types... So if components is not right, find another term for naming this. 
Thanks !

**Comment by MarionPlanque** [comment]
You're right, I think 'Type of views' would be more appropriate then
I'll try to follow this without 'merging' anything this time...
