### ISSUE TITLE
Ghost view

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#277]
@fxi  In this post, a 'shared' view (story map or vector view) refers to the way through the **button 'share this view'** in the view menu (the one that allows sharing a hyperlink), then '**Share in another project**' --> 'Add the view to another project'

_If_:
- a **story map** is created in a project A
- it is shared in a project B
- the **project** A is deleted

_Then_:
-  the **story map** remains visible in the project **B**

This bug only happens for **story maps** and project **deleted**.

**Comment by fxi** [comment]
That's quite strange.

You can maybe split your issue into "ghost views" and "wrong count".

Then, could you make a distinction between shared views types ? There is multiple way of sharing a view:
- URL, the one in your address bar. `?project=xyz&view=abc`
- External view : imported from another project, in the project config
- View published to another project : in the view config, "Other projects where the view is visible" 
- View shared from within a story map.

Then, 
1. If a project is deleted, all related views (stories, raster, vector, custom) are deleted. This could not really go wrong without going unoticed. It could be a cache issue, where a view is requested by a project (external view) and your browser cache has it, so it appear in the list. It should not happen, though.
2. The views count. It's really tricky to do, due to all roles, projects and sharing options... I have to work on it, but I need a fresh brain. And more important than accuracy, it should be quick, as it's one of the most used function in the app, and we can't afford more than a few ms per request. So there is some cached values here and there, which are unvalidated after a bunch of events, but maybe not project removal – @fxi: note to myself, check this out –. In the meantime, if you start a new session after deleting a project, the count should be more accurate.  It sounds easy but it's not :  If someone with a fresh brain read this, please help. Here is the little beast : [code](https://github.com/fxi/map-x-mgl/blob/15d0a5783c0cefd0c511cf304fd2e9e6d980fe56/app/src/helper/db_projects.R#L204)

**Comment by MarionPlanque** [comment]
Great! Thanks! Does it explain the remaining views in the count as well?

**Comment by fxi** [comment]
Maybe. I didn't go that far. There is some cleaning ahead.  I think @thomaspiller could look at it later.

**Comment by MarionPlanque** [comment]
Ok
But all good for this bug? Can I close it?

**Comment by fxi** [comment]
Yep.
