### ISSUE TITLE
New field (unit) in view form

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#29]
### Current Behavior

Unites are specified sometimes on the label and sometimes on the abstract.

### Possible Solution

A new field calls “unite” in the view form could standardize where to put the unites.

**Comment by fxi** [comment]
Thanks.

I think that it's up to the user to define units where she/he need, as sometimes, units should be rendered in labels, and sometimes a simple indication inside a text block above the legend. 

I can indeed add an unit field, but how and where should it be rendered ? You can draw a small mockup and drag the image in the next comment if you need.

Moreover, to be consistant, maybe the best location to but the unit field is in the source attributes metadata instead of the view.

@nicolasray, @PierreLacroix  what do you think ?

**Comment by alejandraarango** [comment]
Normally the units are in the attributes description in the metadata. Often, this attribute description is the same that appears in the text block above the legend. Nevertheless, in the last reunion we were thinking that we can find a way to standardise where the unites appear in the legend. This solution might be less flexible, but at the same time it is more indicative to the layer’s editors and the information is not duplicated several times. 

Another option could be to leave it as it is now (possibility to insert the units in the text box or in the label). However, in the user’s guide/cookbook (proposed in the reunion), it could be recommended to insert the units in the text block instead of in the labels because this can be redundant. 
@nicolasray @PierreLacroix @thomaspiller
