### ISSUE TITLE
PixOp ideas and general improvement

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#338]
## Ideas for long-term improvement
- [ ]	Collateral improvement: 
Allow users to close the pop-up window but keep the filter on with the "x". Add a button "Reset filter and close" to close the pop-up like now. 
- [x] 	Spotlight buffer finer by default.
- [x] 	Allow the user to set whether the overlap should be full or partial (all views overlapping or just at least 2 of them like now).

**Comment by fxi** [comment]
I've added a feature in UI to select between 1,2,3,4,5 or all overlaps. An option was planned since the creation for doing this, but no exposed implementation was available until past week. 
Same approach for overlaps 
https://github.com/fxi/map-x-mgl/blob/fc990bdf93141a0cd2c8c86df3721305a7a253a0/app/src/js/mx_helper_map_pixop.js#L384-L390
and overlaps highlight
https://github.com/fxi/map-x-mgl/blob/fc990bdf93141a0cd2c8c86df3721305a7a253a0/app/src/js/mx_helper_map_pixop.js#L447-L451

**Comment by fxi** [comment]
The select drop down menu specify the number of overlaps to use in the analysis.

For value = 1, all rendered features will be used.
For value = 2, any overlapping parts will be used.
For value = 3, at least 3 layers should overlap.
For value = n, at least n layers should overlap.
For value = all, all layers should overlap.

![overlaps](https://user-images.githubusercontent.com/1196833/46950335-a8bcb500-d084-11e8-8d2a-9353ffbbd825.png)

**Comment by antobenve** [comment]
The issue is closed and the remaining improvement idea is added to issue #383
