### ISSUE TITLE
Map movement when launching MapX - change to still position 

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#341]
- Currently, the map moves from a position A to a position B (defined in the configuration panel of the project) when MapX is launched on the default project or on a specific project. 
Example:
https://app.mapx.org?project=MX-MMN-3EH-CLM-KI7-EG9

- The demanded behavior is to immediately start with map at position B.

- This change should not affect the transition between a project to another one when projects are selected from the projects' list and .

Only change this if it is a super fast job.

**Comment by fxi** [comment]
Initial fit bounds issue.

We have to make it in two steps, because initial bounds is not handled yet.

If the user set his project to a zoom and center very different that the extent settings, the a huge movement will be visible.

If the user put value very close to what zoom+center would be compared to extent, then no movement will be visible.

By the way, two days ago, a commit was pushed in mapbox-gl to solve exactly this !
https://github.com/mapbox/mapbox-gl-js/commit/83aebca5e8266888ed457ae5f1d92b44ba493908

Once available in master, I will implement this. 

Until then, the the user to set matching value in project configuration.

**Comment by antobenve** [comment]
Thanks for the answer. I managed to set a new bound for the UNBIOLAB-WLD project, which was the most important to fix for the time being. When the new implementation will be implemented in your code too I'll check again. Please keep me aware.
