### ISSUE TITLE
"Highlight vector features" - request to change the default mode

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#396]
By default, the button "highlight vector features" highlights *any* feature visible on screen, whereas if users click on that button it is to highlight the areas of overlap.
_Suggestion_: switch the default mode to the option "highlight zones where all areas overlap"

**Comment by fxi** [comment]
Hi @MarionPlanque,

Thanks for this suggestion.

Because the client side overlap tool was not that reliable, I modified it to be a quick highlighting tool, with some overlap functionality for rough estimation. But this overlap functionality should not be seen as the main purpose of this tool. I think keep it "hidden" –– it's two click away, not that hidden – is the best solution. 

Users should instead use the new and fully featured overlap tool : it's much more powerful and reliable. It slower, yes, but do real overlap analysis.

I close this, but feel free to re-open it if needed.

**Comment by MarionPlanque** [comment]
I bring this topic back now we have the proper intersection tool
